# Generated by Django 5.1.6 on 2025-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-circle', help_text='Например: fa-solid fa-apple-alt', max_length=100),
            preserve_default=False,
        ),
    ]
